### ISSUE TITLE
很好，有没有斷語

### ISSUE THREAD

**Issue by flywolfmaster** [creatxrgithub/shu-var-negative#1]
以及虎蛇龙雀玄

**Comment by creatxrgithub** [comment]
有象皆缺，問卜多憂。

六神是附合之神。

《增刪卜易》：千金賦曰﹕虎興而遇吉神不害其吉﹐龍動而逢凶曜難掩其凶。此正理也﹐然則六神而不驗耶乎﹐乃附合之神也﹐卦之吉者逢龍而更吉﹐卦之凶者逢白虎而更凶﹐且元武主盜賊﹐朱雀主口舌﹐無不驗也﹐至於家宅墳塋不可少也。

平日裏最易得驗的是「朱雀」，口舌是非。

https://zh.wikisource.org/wiki/%E5%A2%9E%E5%88%AA%E5%8D%9C%E6%98%93

卜筮原理簡述

卜筮被許多人斥為迷信行為。我卻認為這有一定的道理存在﹐但必須遵從一定的原則。首先﹐「不疑何卜」﹐如果事情沒有其他的選擇必須要做的﹑或是一些常識性的就不用卜了。比如生病了應該找醫生治病﹐想成功就應該努力。「耳鼻眼舌身意」給人帶來了「聽嗅視味触直」覺。且不說第七感等﹐卽使是直覺也會帶來預測的效果。卜筮需要虔誠﹐虔誠的原理是讓人靜心﹐从而體會感覺並將其放大。「一事一日不三卜」是不想讓焦躁的心干擾感覺。當你碰到兩難選擇——兩害相權差不多﹑兩利相權也差不多﹑成事的難易度也差不多的時候——卜筮以聽從心中所欲有何不可。

其實﹐占卜對於一些自身影響大的東西﹐不準確性就大。如果知道要幹什麼﹐準備一下或許就過了。對於有大勢影響的﹑過於依賴別人的﹐知道不好就不做﹐避開就是了。要不然﹐怎麼趨吉避凶。

**Comment by flywolfmaster** [comment]
謝謝，非常有道理。感謝提供代碼。以下我認為還挺全的僅供參考。
![1](https://user-images.githubusercontent.com/86698378/204070977-8abbbd86-186b-44a9-b597-476aa62099f7.jpg)
![2](https://user-images.githubusercontent.com/86698378/204070978-d72e027a-1771-4995-bc60-9d7d829a3d3d.jpg)

**Comment by creatxrgithub** [comment]
我倒是用  ionic + reactjs 差不多寫好一個了。會發到 github 不一定會發到 google play 斷卦大約不會去寫的，起卦方式也僅會有時間起卦及指定卦象。

**Comment by creatxrgithub** [comment]
https://github.com/creatxrgithub/shu-var-app
